# Generated by Django 2.2.1 on 2019-05-22 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exptracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='unspent_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
