# Generated by Django 2.2.1 on 2019-05-23 21:40

from django.conf import settings
import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exptracker', '0004_auto_20190522_1424'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CHARACTER_ADDED', 'CHARACTER_ADDED'), ('CHARACTER_DELETED', 'CHARACTER_DELETED'), ('POINTS_MODIFIED', 'POINTS_MODIFIED'), ('POINTS_SPENT', 'POINTS_SPENT')], max_length=32)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('character', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to='exptracker.Character')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
