# Generated by Django 2.2.1 on 2019-05-24 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exptracker', '0005_logentry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='character',
            old_name='points',
            new_name='stars',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='unspent_points',
            new_name='unspent_stars',
        ),
        migrations.AlterField(
            model_name='logentry',
            name='type',
            field=models.CharField(choices=[('CHARACTER_ADDED', 'CHARACTER_ADDED'), ('CHARACTER_DELETED', 'CHARACTER_DELETED'), ('STARS_MODIFIED', 'STARS_MODIFIED'), ('STARS_SPENT', 'STARS_SPENT')], max_length=32),
        ),
    ]
