# Generated by Django 2.2.1 on 2019-05-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exptracker', '0007_logentry_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logentry',
            name='type',
            field=models.CharField(choices=[('LogType.CHARACTER_ADDED', 'CHARACTER_ADDED'), ('LogType.CHARACTER_DELETED', 'CHARACTER_DELETED'), ('LogType.STARS_ADDED', 'STARS_ADDED'), ('LogType.STARS_SPENT', 'STARS_SPENT')], max_length=32),
        ),
    ]
