# Generated by Django 2.2.1 on 2019-06-10 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exptracker', '0009_auto_20190525_2113'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='dead',
            field=models.BooleanField(default=False),
        ),
    ]
