# Generated by Django 2.2.7 on 2019-11-16 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exptracker', '0011_reformat_20190617_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='iron_man',
            field=models.BooleanField(default=False),
        ),
    ]
